# ==========================================================
# 自造消息队列 · 三节点 Raft 集群
#   node-1 / node-2 / node-3（节点名和容器 DNS 一致， raft 成员表自动生成）
#   MQ_PEERS = Raft 全员表（每节点都要写全 3 员，含自身）
#   身份（王/民）一律由 Raft 选举决定，没有静态角色参数
# ==========================================================
x-mq-peers: &mq-peers "http://node-1:8080,http://node-2:8080,http://node-3:8080"

services:
  node-1:
    image: mq-lab:22
    build: .
    environment:
      MQ_NODE_NAME: node-1
      MQ_SELF: "http://node-1:8080"
      MQ_PEERS: *mq-peers
      MQ_LEADER_URL: "http://node-1:8080"
    ports:
      - "5081:8080"
    volumes:
      - mqlab-leader:/app/data

  node-2:
    image: mq-lab:22
    environment:
      MQ_NODE_NAME: node-2
      MQ_SELF: "http://node-2:8080"
      MQ_PEERS: *mq-peers
      MQ_LEADER_URL: "http://node-1:8080"
    ports:
      - "5082:8080"
    volumes:
      - mqlab-follower-1:/app/data

  node-3:
    image: mq-lab:22
    environment:
      MQ_NODE_NAME: node-3
      MQ_SELF: "http://node-3:8080"
      MQ_PEERS: *mq-peers
      MQ_LEADER_URL: "http://node-1:8080"
    ports:
      - "5083:8080"
    volumes:
      - mqlab-follower-2:/app/data

volumes:
  mqlab-leader:
  mqlab-follower-1:
  mqlab-follower-2: